### PR TITLE
Update quickstart documentation

### PR DESCRIPTION
**Pull request by davidjb**
As per comments at http://stackoverflow.com/questions/29454544/where-to-put-automatic-setup-schema-for-colanderalchemypyramid

### CODE REVIEW

**Comment by davidjb** [comment]
As per the discussion over at https://github.com/tisdall/ColanderAlchemy/commit/0b6714b9237f515efd59a824316ea2900c55f033#commitcomment-10585820

**Comment by tisdall** [comment]
hmm..  I'm pretty sure I remember it working such that after I set it up it automatically generated the `__colanderalchemy__` for each class.  My only reason for not using it was that I found that it was being called more often then I needed (I think on each web request instead of once on server load).  However, I think that was before the SQLAlchemy version change.

BUT, the original code is how it's being called in the test suite, so I'm not sure why there's no failing test cases there then.

**Comment by tisdall** [comment]
yeah, if I make the following change the tests fail:
```
--- a/tests/models.py
+++ b/tests/models.py
@@ -31,7 +31,7 @@ from colanderalchemy import (SQLAlchemySchemaNode, setup_schema)
 Base = declarative_base()
 key = SQLAlchemySchemaNode.sqla_info_key
 
-event.listen(mapper, 'mapper_configured', setup_schema)
+#event.listen(mapper, 'mapper_configured', setup_schema)
 
 
 def has_unique_addresses(node, value):
```
test message:
```
======================================================================
ERROR: test_setup_schema (tests.test_schema.TestsSQLAlchemySchemaNode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/ColanderAlchemy/tests/test_schema.py", line 62, in test_setup_schema
    self.assertIsInstance(cls.__colanderalchemy__,
AttributeError: type object 'Account' has no attribute '__colanderalchemy__'

----------------------------------------------------------------------
```

I think the documentation just needs to be changed to include `from sqlalchemy.orm import mapper`.  Though this alternative usage @ztane has mentioned on StackOverflow would be good to add to the documentation.

**Comment by davidjb** [comment]
Okay, on testing this out, as expected, if you configure the listener against ``sqlalchemy.orm.mapper``, it's called for every model being mapped, attaching Colander schemas to each class.   In the case of the tests, this appears to be what you want since it's a shortcut for having to attach a listener for each individual model.   However, for an application, typically, you would only want a Colander schema for the models your users (and thus your code) interact directly with.

In my case, I have a ``Person`` model with ~20 related classes, and I only want a Colander schema on the ``Person`` class, since this is all I use directly.  The most efficient option is for me to listen for events related to just this class.  If I attached the listener for the ``mapper``, then schemas will be being generated for each of the related classes, resulting in at least an extra 19 schemas I don't need.

These are both potentially valid use cases, but they're very different.   Using ``mapper`` when you don't need a Colander schema on each object is going to lead to lots of wasted processing, but likewise, an application with lots of (or only) user-exposed models may want to set one event listener one time and be done with it.

I've added a commit to this PR that describes both methods.  I personally would only use the targetted approach for efficiency, but my classes are well defined on application startup.

**Comment by tisdall** [comment]
I don't have time to check it right now, but I recall that I stopped using that method because I found that it was being called more than once.  In my code I manually generate the schema on load and then never again.

Any way, I think it's good to document both parts and keep people informed.  ;)

**Comment by tisdall** [comment]
The docs are now updated...  it seems that the build died because of an issue at ReadTheDocs and I had to manually re-build it.

**Pull request merged**
