### PR TITLE
Exclude tests from package install

### PR DESCRIPTION
**Pull request by ronnix**
We don't want the `tests` directory to end up in `site-packages` on package install.

### CODE REVIEW

**Comment by tisdall** [comment]
Makes sense.  Did this cause any sort of issue, though?

**Comment by ronnix** [comment]
No issues for me, but I guess it could conflict if two packages both want to install `tests/test_foo.py`...

**Comment by tisdall** [comment]
I was just wondering what prompted the PR.  Most PR's come about because of some issue the developer ran across.

**Comment by ronnix** [comment]
Well, when using Sublime Text I like to have my virtualenv's `site-packages` folder open in the project in addition to my own source code. It makes it easier to jump quickly to a library's source code when needed, or to to code completion. While browsing the contents of this `site-packages` directory in the sidebar, I stumbled upon a `tests` directory that shouldn't be there. I then tracked which package had put it there, and did a quick friendly PR. :)

**Pull request merged**
